config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users', sessions: 'sessions' }
  
  resources :photo_grams
  resources :photo_grams do
    resources :likes, only: [:create, :destroy]
  end
  root to:"photo_grams#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo_gram
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo_gram
end

app/models/photo_gram.rb
class PhotoGram < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :likes
    attr_accessor :user_id
end

app/models/photogram.rb
class Photogram < ApplicationRecord
    belongs_to :user
    has_many :comments
    has_many :likes
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  has_many :photo_grams
  has_many :comments
  has_many :likes
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_grams_controller.rb
class PhotoGramsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_blog_post, only: [:edit, :update, :destroy]
    def index
        @photo_grams = PhotoGram.all
    end

    def show
        @photo_gram = PhotoGram.find(params[:id])
    end
    def new
        @photo_gram = PhotoGram.new
    end

    def create
        @photo_gram = current_user.photo_grams.build(photo_gram_params)
        if @photo_gram.save
            redirect_to @photo_gram
        else
            render :new
        end

    end

    def edit
        
    end

    def update
        if @photo_gram.update(photo_gram_params)
            redirect_to @photo_gram
        else
            render :edit
        end
    end
    def destroy
        @photo_gram.destroy
        redirect_to photo_gram_url
    end

    private

    def set_photo_gram
        @photo_gram = current_user.photo_grams.find(params[:id])
    end

    
    def photo_gram_params
        params.require(:photo_gram).permit(:title)
    end
      

    
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
  
    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :gender, :dob, :avatar)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    skip_before_action :verify_authenticity_token, only: %i[create destroy]
  
    def create
      user = User.find_for_database_authentication(email: params[:user][:email])
      if user && user.valid_password?(params[:user][:password])
        sign_in(user)
        redirect_to photo_grams_path
      else
        render json: { error: 'Invalid email or password' }, status: :unauthorized
      end
    end
  
    def destroy
      sign_out(current_user)
  
      redirect_to blog_posts_path, notice: 'logged out successfully !!.'
    end
  end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  
  
  private

  def sign_up_params
    params.require(:user).permit(:name, :dob, :gender, :email, :password, :password_confirmation, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photograms_helper.rb
module PhotogramsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photogram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo_grams/_form.html.erb
<div class="post">
    <%= form_with model: @photo_gram do |form|%>
        <% if form.object.errors.any? %>
            <div>
                <% form.object.errors.full_messages.each do |message| %>
                    <div><%= message %></div>
                <% end %>
            </div>
            <div class="field" >
                <%= form.label :image %>
                <%= form.file_field :image %>
            </div>
        <% end %>
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>

        
        <div class="field">
            <%= form.label :image %>
            <%= form.file_field :image %>
        </div>

        <div class="field">
            <%= form.label :video %>
            <%= form.file_field :video %>
        </div>



        <div class="actions">
            <%= form.submit %>
        </div>

    <% end %>
</div>

app/views/photo_grams/edit.html.erb
<div>
    <div class="form"><%= render partial: "form", local: {photo_gram: @photo_gram} %></div><br/>
    
        <%= button_to "Delete", @photo_gram, method: :delete %><br/>
        <div class="back">
            <%= link_to 'Show', @photo_gram %><br/>
        </div>
        <div class=back>
        <%= link_to 'Back', @photo_gram_path %><br/>
        </div>
</div>  

app/views/photo_grams/index.html.erb
<div class="photo_gram-container">

  <%= link_to 'Create New Post', new_photo_gram_path %>

  <% @photo_grams.each do |photo_gram| %>

    <div class="post">

      <% if photo_gram.image.attached? %>
        <%= image_tag photo_gram.image, class: 'photo_gram-image' , width: "20%"%>
      <% else %>
        <p>No image available. </p>
      <% end%>     
      <%= photo_gram.content %>
    </div>
    
  <% end %> 
</div>
<body>
	<nav class="navbar">
		<div class="navdiv">
			<div class="logo"><a href="#">SOCIALBOOK</a> </div>
			<ul>
				<li><a href="#">Home</a></li>
				<li><a href="#">About</a></li>
				<li><a href="#">Contact</a></li>
				<li>
        <% if user_signed_in? %>
          <%= button_to 'Signout', destroy_user_session_path, method: :delete, form: {turbolink: false} %>
        <% else %>
          <p>You are not logged in.</p>
        <% end %>
        </li>
			</ul>
		</div>
	</nav>
</body>



<% if user_signed_in? %>
  <p>Logged in as: <%= current_user.email %></p>
<% else %>
  <p>You are not logged in.</p>
<% end %>

<%= link_to ' Create post', new_photo_gram_path %>


  <% @photo_grams.each do |photo_gram| %>
    <div class="side">
      <div class="post-container">
        <div class="post">
          <p><strong><%= post.user.username %></strong></p>
          <% if post.user.avatar? %>
            <%= image_tag post.user.avatar.url, class: "avatar" %>
          <% else %>
            <div class="default-avatar"><img src="https://www.pngarts.com/files/11/Avatar-PNG-Picture.png" alt="default-avatar" class="default-avatar"></div>
          <% end %>
          <p><%= post.user.email %>.   .   .</p>
          <br>
          <p>
          <% unless current_user == post.user %>
            <% if current_user.following?(post.user) %>
              <%= button_to 'Unfollow', friendship_path(post.user.id), method: :delete %>
            <% else %>
              <%= button_to 'Follow', friendships_path(post.user.id), method: :post %>
            <% end %>
          <% end %>
          </p>
        </div>
        <h1><%= link_to post.content, post_path(post) %></h1>
        <%= render 'post', post: post %>
        
      </div>
    </div>
    
  <% end %>

app/views/photo_grams/new.html.erb
<div class="new">
    <div class="form">
        <%= render 'form' %>
    </div>

    <div class ="back" >
        <%= link_to'back', @photo_gram_path %>
    </div>
</div>

app/views/photo_grams/photo_gram.html.erb
 
  

  <% if photo_gram.image.present? %>
    <div >
      <%= image_tag photo_gram.image.url ,width: "100%" %>
    </div>
  <% end %>

  <% if photo_gram.video.present? %>
    <video controls , width="30%">
    <source src="<%= photo_gram.video.url %>" type="video/mp4">
    </video>
  <% end %>
  <h3>Comments:</h3>
    <ul>
        <% photo_gram.comments.each do |comment| %>
          <li> <p><strong><%= comment.user.email %></strong>:</strong> <%= comment.content %></p></li>
        <% end %>
    </ul>
    <% if photo_gram.liking_users.any? %>
      <h3>Liking Users:</h3>
      <ul>
        <% photo_gram.liking_users.each do |user| %>
          <li><%= user.email %></li><br>
          <% end %>
      </ul>
    <% end %>


app/views/photo_grams/show.html.erb
<div class="post">
    <p>
        <strong>Title:</strong>
        <%= @photo_gram.title%>
    </p>

    <p>
        <strong>Content:</strong>
        <%= @photo_gram.content%>
    </p>
    
    <div class="image">
        <% if @photo_gram.image.present? %>
            <p>
                <strong>Image:</strong>
                <%= image_tag @photo_gram.image ,width:"50%"%>
            </p>
        <% end %>
    </div>
</div> 
<%= button_to 'Delete', photo_gram_path(@photo_gram), method: :delete, data: { confirm: 'Are you sure you want to log out?' } %> <br/>
<%= link_to 'Edit', edit_photo_gram_path(@photo_gram) %> |
<%= link_to 'Back', photo_grams_path %>
  